version: "3.9"
services:
  apidocker:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - TESSDATA_PREFIX=/code    
    #links:
      #- Monguito
  #Monguito:
  #  image: mongo
  #  ports:
  #    - "27017:27017"
  #  volumes:
  #    - mongo-data:/data/db
      #/var/lib/mysql
      #/var/lib/postgesql/
      #/var/lib/mariadb/
#volumes:
#  mongo-data:


#sudo docker create -it --name space-stone -e "TESSDATA_PREFIX=/app" -v "$PWD":/app -w /app clearlinux/tesseract-ocr tesseract Untitled4_20221109223549.png stdout --oem 1